services:
  - type: web
    name: goEat-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: PORT
        value: 8080
      - key: MONGO_URI
        sync: false
